In [ ]:
import numpy as np

In [ ]:
#logistic regression

class logisticRegression():
  def __init__(self, learningRate, iterations):
    self.learningRate = learningRate
    self.iterations = iterations


  def fit(self, X, Y):
    self.m, self.n = X.shape
    self.w = np.zeros(self.n)
    self.b = 0
    self.X = X
    self.Y = Y

    #implementing gradient descent
    for i in range(self.iterations):
      self.update_weights()

  def update_weights(self):

    #calculate gradients
    y_pred = self.predict(self.X)
    dw = (1/self.m)*np.dot(self.X.T, (y_pred - self.Y))
    db = (1/self.m)*np.sum(y_pred - self.Y)

    #updating weights

    self.w = self.w - self.learningRate*dw
    self.b = self.b - self.learningRate*db


  def predict(self, X):

    z = (X.dot(self.w) + self.b)
    y_pred = 1 / (1 + np.exp(-z))
    y_pred = np.where(y_pred > 0.5, 1, 0)
    return y_pred

In [ ]:
#implementing logistic regression model
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

In [ ]:
df = pd.read_csv('diabetes.csv')

In [ ]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [ ]:
df.shape

(768, 9)

In [ ]:
x = df.drop('Outcome', axis=1)
y = df['Outcome']

In [ ]:
#stanadardization
scaler = StandardScaler()
x = scaler.fit_transform(x)

In [ ]:
print(y)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [ ]:
#splitting it into training amd test set
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2)

In [ ]:
print(x.shape, x_train.shape, x_test.shape)

(768, 8) (614, 8) (154, 8)

In [ ]:
model = logisticRegression(learningRate=0.01, iterations=1000)

In [ ]:
model.fit(x_train, y_train)

In [ ]:
#evaluation
y_pred = model.predict(x_train)
train_acc = accuracy_score(y_train, y_pred)
print(train_acc)

0.6905537459283387

In [ ]:
#accuracy score on test set

y_pred = model.predict(x_test)
test_acc = accuracy_score(y_test, y_pred)
print(test_acc)

0.7142857142857143

In [94]:
#making predictive system

input = (1,97,66,15,140,23.2,0.487,22)
array_input = np.asarray(input)
reshaped_input = array_input.reshape(1, -1)
std_data = scaler.transform(reshaped_input)
prediction = model.predict(std_data)
if prediction[0] == 0:
  print('non-diabetic')
else:
  print('diabetic')

non-diabetic

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(